### ISSUE TITLE
Exception Timestamp error with inverter data

### ISSUE THREAD

**Issue by fahimmac** [jbuehl/solaredge#49]
Hi all,

I encountered this problem previously but it seems to be back again.

I was trying to use semonitor.py with my SolarEdge inverter. While using the -c 322 command with semonitor.py i can get energy values from the inverter.

But while trying to get the raw values from inverter, i came across a timestamp exception. The logging was working fine in last couple of days but now i am having this error.

sudo python semonitor.py -m -x -s 07e12a1d2 -d stdout -vvvv -t 4 /dev/ttyUSB1

Aug 29 08:49:04 debugEnable: True 
Aug 29 08:49:04 debugFiles: True 
Aug 29 08:49:04 debugMsgs: True 
Aug 29 08:49:04 debugData: True 
Aug 29 08:49:04 debugRaw: True 
Aug 29 08:49:04 debugFileName: stdout 
Aug 29 08:49:04 haltOnException: True 
Aug 29 08:49:04 inFileName: /dev/ttyUSB1 
Aug 29 08:49:04 inputType: 4 
Aug 29 08:49:04 serialDevice: True 
Aug 29 08:49:04     baudRate: 115200 
Aug 29 08:49:04 networkDevice: False 
Aug 29 08:49:04 sePort: 22222 
Aug 29 08:49:04 networkSvcs: False 
Aug 29 08:49:04 following: True 
Aug 29 08:49:04 passiveMode: False 
Aug 29 08:49:04 commandAction: False 
Aug 29 08:49:04 masterMode: True 
Aug 29 08:49:04 slaveAddrs: 07e12a1d2 
Aug 29 08:49:04 outFileName: stdout 
Aug 29 08:49:04 append: w 
Aug 29 08:49:04 opening /dev/ttyUSB1 
Aug 29 08:49:05 starting read thread 
Aug 29 08:49:05 starting master thread 
Aug 29 08:49:05 dataLen:    0000 
Aug 29 08:49:05 dataLenInv: ffff 
Aug 29 08:49:05 sequence:   017d 
Aug 29 08:49:05 source:     fffffffe 
Aug 29 08:49:05 dest:       7e12a1d2 
Aug 29 08:49:05 function:   0302 
Aug 29 08:49:05 /dev/ttyUSB1 <-- message: 1 length: 22 
Aug 29 08:49:05 data:       12 34 56 79 00 00 ff ff 7d 01 fe ff ff ff d2 a1 
Aug 29 08:49:05 data:       12 7e 02 03 04 8a 
Aug 29 08:49:05   
Aug 29 08:49:15 RS485 master ack timeout 
Aug 29 08:49:15 Exception: timestamp out of range for platform time_t 
Aug 29 08:49:15 data:       f8 01 07 fe 26 02 d2 a1 12 7e fe ff ff ff 00 05 
Aug 29 08:49:15 data:       80 00 a9 66 3e 20 0d 00 ce d0 9f 59 75 23 13 82 
Aug 29 08:49:15 data:       e5 26 65 03 0e 80 00 40 5f 3e 20 0d 00 de d0 9f 
Aug 29 08:49:15 data:       59 b1 23 3d d6 e2 0d b6 02 0e 80 00 23 63 3e 20 
Aug 29 08:49:15 data:       0d 00 e2 d0 9f 59 98 23 02 56 65 26 1c 03 0f 80 
Aug 29 08:49:15 data:       00 19 62 3e 20 0d 00 f1 d0 9f 59 e6 23 02 ba e6 
Aug 29 08:49:15 data:       23 29 03 0d 80 00 a5 52 3f 20 0d 00 f2 d0 9f 59 
Aug 29 08:49:15 data:       e7 19 02 46 c5 26 cb 02 0f 80 00 65 59 3f 20 0d 
Aug 29 08:49:15 data:       00 fa d0 9f 59 bb 23 07 3a 15 26 36 03 0f 80 00 
Aug 29 08:49:15 data:       f9 5e 3e 20 0d 00 fe d0 9f 59 3b 23 fe 75 e6 17 
Aug 29 08:49:15 data:       21 02 0d 80 00 e4 5f 3e 20 0d 00 09 d1 9f 59 7b 
Aug 29 08:49:15 data:       23 01 76 36 18 3c 02 0d 80 00 ed 60 3e 20 0d 00 
Aug 29 08:49:15 data:       0c d1 9f 59 35 23 30 16 55 11 f0 01 0e 80 00 25 
Aug 29 08:49:15 data:       61 3e 20 0d 00 10 d1 9f 59 ee 23 04 ba 75 2a b4 
Aug 29 08:49:15 data:       03 0e 80 00 89 66 3e 20 0d 00 14 d1 9f 59 4f 19 
Aug 29 08:49:15 data:       ff b9 25 2a 64 03 0e 80 00 be 66 3e 20 0d 00 15 
Aug 29 08:49:15 data:       d1 9f 59 f7 23 0a a2 45 28 77 03 0e 80 00 29 62 
Aug 29 08:49:15 data:       3e 20 0d 00 17 d1 9f 59 f0 23 46 1a 22 0a ca 02 
Aug 29 08:49:15 data:       0e 80 00 f7 57 3f 20 0d 00 39 d1 9f 59 ed 23 10 
Aug 29 08:49:15 data:       4e d5 25 0b 03 0f 80 00 db 64 3e 20 0d 00 47 d1 
Aug 29 08:49:15 data:       9f 59 5c 23 f6 e9 25 17 10 02 0d 80 00 98 52 3f 
Aug 29 08:49:15 data:       20 0d 00 4a d1 9f 59 15 24 03 42 65 26 fe 02 0f 
Aug 29 08:49:15 data:       80 00 3f 5f 3e 20 0d 00 4b d1 9f 59 5a 23 39 6e 
Aug 29 08:49:15 data:       e2 07 c7 01 0f 80 00 83 66 3e 20 0d 00 4d d1 9f 
Aug 29 08:49:15 data:       59 b8 15 fe e9 f5 16 e1 01 0d 80 00 1d 66 3e 20 
Aug 29 08:49:15 data:       0d 00 4e d1 9f 59 46 24 aa 61 95 23 d3 02 0d 80 
Aug 29 08:49:15 data:       00 2a 64 3e 20 0d 00 50 d1 9f 59 da 23 32 66 72 
Aug 29 08:49:16 data:       08 ba 01 0d 80 00 66 64 3e 20 0d 00 53 d1 9f 59 
Aug 29 08:49:16 data:       b0 23 3c d6 e2 09 d2 01 0e 80 00 4f 62 3e 20 0d 
Aug 29 08:49:16 data:       00 54 d1 9f 59 95 23 fa 51 a6 18 f9 01 0d 80 00 
Aug 29 08:49:16 data:       f8 5e 3e 20 0d 00 60 d1 9f 99 91 23 02 e2 85 16 
Aug 29 08:49:16 data:       f1 01 0d 80 00 4f 69 3e 20 0d 00 69 d1 9f 59 a8 
Aug 29 08:49:16 data:       24 9e 39 a5 23 6f 03 0f ff 6c 
Exception in thread read thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "semonitor.py", line 40, in readData
    processMsg(msg, dataFile, recFile, outFile)
  File "semonitor.py", line 56, in processMsg
    msgData = parseData(function, data)
  File "/home/pi/inverter/sedgenew/seData.py", line 22, in parseData
    return parseDeviceData(data)
  File "/home/pi/inverter/sedgenew/seData.py", line 138, in parseDeviceData
    optDict[seId] = parseNewOptData(seId, optItems, data[dataPtr:dataPtr+devLen])
  File "/home/pi/inverter/sedgenew/seData.py", line 204, in parseNewOptData
    return devDataDict(seId, optItems, [timeStamp, 0, uptime, vpan, vopt, imod, eday, temp])
  File "/home/pi/inverter/sedgenew/seData.py", line 209, in devDataDict
    devDict["Date"] = formatDateStamp(itemValues[0])
  File "/home/pi/inverter/sedgenew/seData.py", line 233, in formatDateStamp
    return time.strftime("%Y-%m-%d", time.localtime(timeStamp))
ValueError: timestamp out of range for platform time_t

Any help would be really great.

Thanks a lot in advance.

**Comment by fahimmac** [comment]
i have divide the timestamp with 1000. It looks like this

return time.strftime("%Y-%m-%d", time.localtime(timeStamp/1000))

Now i am getting the raw data from the inverter. Though the time is a bit scrambled, but i do not need it at this moment.
